-- CareReady Ontario learner data schema
-- Apply this migration to the Supabase project before enabling production accounts.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  profession text not null default 'Healthcare professional',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null,
  lesson_id text not null,
  completed boolean not null default false,
  score integer check (score between 0 and 100),
  updated_at timestamptz not null default now(),
  unique (user_id, module_id, lesson_id)
);

create table if not exists public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null,
  lesson_id text not null,
  score integer not null check (score between 0 and 100),
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.protocol_acknowledgements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  protocol_id text not null,
  acknowledged_at timestamptz not null default now(),
  review_due_at timestamptz,
  unique (user_id, protocol_id)
);

create index if not exists lesson_progress_user_id_idx
  on public.lesson_progress(user_id);
create index if not exists quiz_attempts_user_id_idx
  on public.quiz_attempts(user_id);
create index if not exists protocol_acknowledgements_user_id_idx
  on public.protocol_acknowledgements(user_id);

alter table public.profiles enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.protocol_acknowledgements enable row level security;

create policy "Learners can view their profile"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id);
create policy "Learners can update their profile"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Learners can view their progress"
  on public.lesson_progress for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Learners can create their progress"
  on public.lesson_progress for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "Learners can update their progress"
  on public.lesson_progress for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Learners can view their quiz attempts"
  on public.quiz_attempts for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Learners can create their quiz attempts"
  on public.quiz_attempts for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Learners can view their protocol acknowledgements"
  on public.protocol_acknowledgements for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Learners can create acknowledgements"
  on public.protocol_acknowledgements for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "Learners can update acknowledgements"
  on public.protocol_acknowledgements for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, profession)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'profession', 'Healthcare professional')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
